<a href="https://colab.research.google.com/github/kajall120/Data_science_Lab_SE_64/blob/main/ex5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("/content/test (2)(5).csv")
print(df.head())

   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female
2          894       2                     Myles, Mr. Thomas Francis    male
3          895       3                              Wirz, Mr. Albert    male
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked
0  34.5      0      0   330911   7.8292   NaN        Q
1  47.0      1      0   363272   7.0000   NaN        S
2  62.0      0      0   240276   9.6875   NaN        Q
3  27.0      0      0   315154   8.6625   NaN        S
4  22.0      1      1  3101298  12.2875   NaN        S

In [3]:
print("\nDataset Information:")
print(df.info())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB
None

In [16]:
filter = df[df['Fare'] > 50]
print("Passengers with Fare > 50:")
print(filter.head())

Passengers with Fare > 50:
    PassengerId  Pclass                                               Name  \
12          904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)
14          906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...
20          912       1                             Rothschild, Mr. Martin
23          915       1                    Williams, Mr. Richard Norris II
24          916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)

       Sex   Age  SibSp  Parch       Ticket      Fare            Cabin  \
12  female  23.0      1      0        21228   82.2667              B45
14  female  47.0      1      0  W.E.P. 5734   61.1750              E31
20    male  55.0      1      0     PC 17603   59.4000              NaN
23    male  21.0      0      1     PC 17597   61.3792              NaN
24  female  48.0      1      3     PC 17608  262.3750  B57 B59 B63 B66

   Embarked
12        S
14        S
20        C
23        C
24        C

In [7]:
df.groupby('Pclass')['Fare'].mean()

Pclass
1    94.280297
2    22.202104
3    12.459678
Name: Fare, dtype: float64

In [10]:
numeric_cols = df.select_dtypes(include=np.number).columns
df.agg({
    col: ['sum', 'mean', 'min', 'max', 'count']
    for col in numeric_cols
})

,PassengerId,Pclass,Age,SibSp,Parch,Fare
sum,460009.0,947.00000,10050.50000,187.000000,164.000000,14856.537600
mean,1100.5,2.26555,30.27259,0.447368,0.392344,35.627188
min,892.0,1.00000,0.17000,0.000000,0.000000,0.000000
max,1309.0,3.00000,76.00000,8.000000,9.000000,512.329200
count,418.0,418.00000,332.00000,418.000000,418.000000,417.000000